### ISSUE TITLE
Feature Request - Adicionar opção de setar a interface

### ISSUE THREAD

**Issue by hamiltoncneto** [ustrajunior/keepup#1]
Seria interessante ter uma opção no arquivo de configuração, onde eu informasse a interface de rede que gostaria que ele observasse o ip.

Por exemplo:
cfEther: wlan0

Obrigado.

**Comment by joseustra** [comment]
Interessante. Estou fazendo um refactor e vou adicionar isso nas funcionalidades.

**Comment by joseustra** [comment]
Agora consegue pegar o ip da interface setada no arquivo de configuração.

**Comment by hamiltoncneto** [comment]
Já atualizei aqui o/
